### ISSUE TITLE
Misleading description causes confusion among students

### ISSUE THREAD

**Issue by Corb3nik** [Enteris/GLO2001-TP2#3]
Hello,

The description of this project is misleading and could cause confusion among students.

In fact, students looking for public GLO2001 projects might stumble upon this repo and think that this repo is private when in fact, it isn't.

I suggest the following fix :
```
Repo public pour le cours d'OS TP2
```

Regards,

Corb3nik

**Comment by Enteris** [comment]
Done, thanks dear sir! :P
